/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 0.1.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// sw "github.com/nbckr/HoloRepository-Core/HoloStorageAccessor/go"
	sw "./go"
)

func main() {
	router := sw.NewRouter("config.json")

	log.Fatal(router.Run(":8080"))
}
