/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AuthorsAidGet - Get a single author metadata in HoloStorage
func AuthorsAidGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AuthorsAidPut - Add or update author information
func AuthorsAidPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AuthorsGet - Mass query for author metadata in HoloStorage
func AuthorsGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HologramsGet - Mass query for hologram metadata based on hologram ids
func HologramsGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HologramsHidDelete - Delete a hologram in HoloStorage
func HologramsHidDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HologramsHidDownloadGet - Download holograms models based on the hologram id
func HologramsHidDownloadGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HologramsHidGet - Get a single hologram metadata based on the hologram id
func HologramsHidGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HologramsPost - Upload hologram to HoloStorage
func HologramsPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatientsGet - Mass query for patients metadata in HoloStorage
func PatientsGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatientsPidGet - Get a single patient metadata in HoloStorage
func PatientsPidGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatientsPidPut - Add or update basic patient information
func PatientsPidPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
