/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Author - Who authored the Hologram
type Author struct {

	// The author ID
	Aid string `json:"aid,omitempty"`

	Name PersonName `json:"name,omitempty"`
}
