/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PersonName - Components that make up the name of a person
type PersonName struct {

	Full string `json:"full,omitempty"`

	Title string `json:"title,omitempty"`

	Given string `json:"given,omitempty"`

	Family string `json:"family,omitempty"`
}
