/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Patient - Metadata of a single patient
type Patient struct {

	Pid string `json:"pid,omitempty"`

	Gender string `json:"gender,omitempty"`

	BirthDate string `json:"birthDate,omitempty"`

	Name PersonName `json:"name,omitempty"`
}
