/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
	"os"
)

// HologramUploadData - Data structure to upload holograms to HoloStorage
type HologramUploadData struct {

	// Summary of the hologram
	Title string `json:"title,omitempty"`

	// Further elaborations on the hologram with additional details
	Description string `json:"description,omitempty"`

	// The mimetype of the hologram file
	ContentType string `json:"contentType,omitempty"`

	// The size of the hologram in KB
	FileSizeInKb int32 `json:"fileSizeInKb,omitempty"`

	// The body part the hologram represents
	BodySite string `json:"bodySite,omitempty"`

	// The date when the imaging was done
	DateOfImaging time.Time `json:"dateOfImaging,omitempty"`

	// The date the hologram was generated
	CreationDate time.Time `json:"creationDate,omitempty"`

	// The way the hologram was created
	CreationMode string `json:"creationMode,omitempty"`

	// The description associated with the creation method of the hologram
	CreationDescription string `json:"creationDescription,omitempty"`

	// The raw binary of the hologram model
	HologramFile *os.File `json:"hologramFile,omitempty"`

	Author Author `json:"author,omitempty"`

	Patient Patient `json:"patient,omitempty"`
}
