/*
 * HoloStorage Accessor API
 *
 * API to access holograms and metadata from HoloStorage
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// sw "github.com/nbckr/HoloRepository-Core/HoloStorageAccessor/go"
	sw "../../internal/openapi"
)

func main() {
	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
